### ISSUE TITLE
Preview button gone after new Lokalise release

### ISSUE THREAD

**Issue by gfarago** [lokalise-document-preview/browser-extension#8]
Hi,

Today Lokalise released some interface changes, and now the Preview button is gone. Confirmed by other users in the team. Hope it's just because of te rearranged screen layout...

Best,
Gabor Farago
espell translation & localization ltd.

**Comment by gfarago** [comment]
The extension is still working (v3.0.0) as it offers the special link editing fields, only the Preview button is gone (probably with the addition of the task menu instead of icons).

**Comment by terales** [comment]
@gfarago  Thanks for reporting! Would fix it this weekend.

**Comment by terales** [comment]
Submitted a fixed extension to the Chrome Web Store, once the version 3.0.1 would be approved the preview button would go back
